"""Race several policies on the SAME LSY protocol and compare them — Lesson 5 §4.

One model's lap time is a number; two models' lap times are a *claim*. This
script makes the comparison honest by construction: every model flies the same
config, the same number of episodes, scored by the race's own `simulate()` —
the exact loop `scripts/evaluate.py` uses — never a re-implementation of it.

Run in the RACE venv, with your completed race_bridge.py already copied into
repos/lsy_drone_racing/lsy_drone_racing/control/ and `control_mode = "attitude"`
set in the config you pass (both from Lesson 3 §4):

    /opt/venvs/race/bin/python tasks/racing/code/compare_models.py \
        --episodes 20 --config level0.toml \
        v5_s0=tasks/racing/crazy_track/results/<run-a>/datt_ppo_final.zip \
        v5_s1=tasks/racing/crazy_track/results/<run-b>/datt_ppo_final.zip \
        v5_s2=tasks/racing/crazy_track/results/<run-c>/datt_ppo_final.zip

Each positional argument is  label=path/to/policy.zip.

Lesson 6 -- compare MODEL-BASED trackers through race_bridge_mpc.py instead: name the
bridge and give controller SPECS (anything that is not a .zip is handed to the bridge as
RACE_CONTROLLER; its other knobs -- RACE_CRUISE, RACE_PLAN, RACE_TAKEOFF_T -- are
inherited from your shell, so one comparison changes one thing):

    RACE_CRUISE=2.5 /opt/venvs/race/bin/python tasks/racing/code/compare_models.py \
        --bridge race_bridge_mpc.py --episodes 20 --config level0.toml \
        mpc=mpc eso=mpc_offsetfree l1=mpc_l1

Outputs (in --out-dir, default tasks/racing/figures/):
    comparison.csv         per-episode times, every model, every episode
    comparison.png         lap times (dots = episodes, bar = mean over
                           successes) and success rate, side by side
    <label>/flown_ep*.csv  each model's flown paths (for plot_trajectory.py)

What the numbers mean (same rules as the leaderboard, Lesson 3 §3):
  * an episode counts only if ALL gates are passed; failures score None
  * a model below 50 % success is NOT ranked — a fast crash is not a lap
  * mean is over successful episodes only, so always read it NEXT TO the
    success rate, never alone
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path

import numpy as np

LSY = Path("/workspace/repos/lsy_drone_racing")

# Single-measure charts use one calm hue; identity lives in the axis labels.
BAR = "#5B7FA6"
DOT = "#2B3A4A"


def hover_start_config(config: str) -> str:
    """Write <stem>_hoverstart.toml next to the level config: the same race with the drone
    placed at rest at hover height (z = 1.0) instead of on the ground (Lesson 7 section 1).
    Everything else -- gates, poles, randomisation, the 50 Hz loop, the contacts -- stays.
    The bridges detect the height and skip their takeoff leg (RACE_START=auto)."""
    import re

    src = LSY / "config" / config
    text = src.read_text()
    m = re.search(r"(\[\[env\.track\.drones\]\]\s*\npos = \[)([^\]]*)(\])", text)
    if m is None:
        sys.exit(f"{src}: no [[env.track.drones]] pos entry to rewrite")
    x, y, _z = (v.strip() for v in m.group(2).split(","))
    text = text[:m.start(2)] + f"{x}, {y}, 1.0" + text[m.end(2):]
    out = src.with_name(f"{src.stem}_hoverstart.toml")
    out.write_text("# GENERATED by tasks/racing/code/compare_models.py --start hover: "
                   "the drone starts at rest at hover height.\n" + text)
    return out.name


def is_policy_path(value: str) -> bool:
    """A bare policy .zip (for race_bridge.py) vs a controller spec such as `mpc` or
    `datt:<zip>` (for race_bridge_mpc.py, Lesson 6/7)."""
    return value.endswith(".zip") and not value.startswith(("datt:", "datt_acro:", "datt_rnn:"))


def no_poles_config(config: str) -> str:
    """Write <stem>_nopoles.toml next to the level config: the same race with the four obstacle
    poles moved to the arena corners (inside the safety limits, far from every gate), i.e. the
    pole-free benchmark of Lesson 7 section 4. Gate frames, randomisation and the clock stay.
    (lsy expects the obstacle list to keep its length; relocating is the safe way to "remove".)"""
    import re

    src = LSY / "config" / config
    text = src.read_text()
    corners = ["[-2.3, 1.3, 1.55]", "[2.3, 1.3, 1.55]", "[-2.3, -1.3, 1.55]", "[2.3, -1.3, 1.55]"]
    n = 0

    def repl(m):
        nonlocal n
        pos = corners[n % len(corners)]
        n += 1
        return m.group(1) + pos

    text = re.sub(r"(\[\[env\.track\.obstacles\]\]\s*\npos = )\[[^\]]*\]", repl, text)
    if n == 0:
        sys.exit(f"{src}: no [[env.track.obstacles]] entries to relocate")
    out = src.with_name(f"{src.stem}_nopoles.toml")
    out.write_text("# GENERATED by tasks/racing/code/compare_models.py --no-poles: the obstacle poles "
                   "stand in the arena corners, out of every lap's way.\n" + text)
    return out.name


def race(model: str, episodes: int, config: str, log_dir: Path,
         bridge: str = "race_bridge.py") -> list:
    """Fly `episodes` races with `bridge` driving `model` -- a policy .zip for
    race_bridge.py, a controller spec for race_bridge_mpc.py (Lesson 6). Their loop."""
    if is_policy_path(model):
        os.environ["RACE_MODEL"] = str(Path(model).resolve())
        os.environ.pop("RACE_CONTROLLER", None)
    else:                                   # a controller spec for race_bridge_mpc.py
        os.environ["RACE_CONTROLLER"] = model
        os.environ.pop("RACE_MODEL", None)
    os.environ["RACE_LOG_DIR"] = str(log_dir)
    # Stale flown-lap logs from a previous run would shift the episode indices.
    if log_dir.exists():
        for old in log_dir.glob("flown_ep*.csv"):
            old.unlink()
    sys.path.insert(0, str(LSY / "scripts"))
    from sim import simulate  # lsy's own runner — the protocol, not a copy

    return simulate(config=config, controller=bridge,
                    n_runs=episodes, render=False)


def summarize(label: str, times: list) -> dict:
    ok = [t for t in times if t is not None]
    n = len(times)
    return {
        "label": label,
        "episodes": n,
        "successes": len(ok),
        "success_rate": len(ok) / n if n else 0.0,
        "mean": float(np.mean(ok)) if ok else float("nan"),
        "std": float(np.std(ok)) if ok else float("nan"),
        "best": float(np.min(ok)) if ok else float("nan"),
        "times": times,
    }


def figure(rows: list[dict], out: Path):
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    labels = [r["label"] for r in rows]
    x = np.arange(len(rows))

    fig, (ax_t, ax_s) = plt.subplots(
        1, 2, figsize=(10, 4.5), gridspec_kw={"width_ratios": [3, 2]})

    # Lap times: every successful episode as a dot, the mean as a thin bar.
    for i, r in enumerate(rows):
        ok = np.array([t for t in r["times"] if t is not None], dtype=float)
        if len(ok):
            jitter = (np.random.default_rng(i).random(len(ok)) - 0.5) * 0.18
            ax_t.plot(np.full(len(ok), x[i]) + jitter, ok, "o", ms=5,
                      color=DOT, alpha=0.55, zorder=3)
            ax_t.bar(x[i], r["mean"], width=0.55, color=BAR, alpha=0.35,
                     zorder=1)
            ax_t.errorbar(x[i], r["mean"], yerr=r["std"], fmt="none",
                          ecolor=DOT, capsize=4, lw=1.2, zorder=4)
            ax_t.annotate(f"{r['mean']:.2f}±{r['std']:.2f}",
                          (x[i], r["mean"]), textcoords="offset points",
                          xytext=(0, 8), ha="center", fontsize=9)
    ax_t.set_xticks(x, labels)
    ax_t.set_ylabel("lap time  (s)   — successful episodes only")
    ax_t.set_title("Lap times (dot = one episode)")
    ax_t.grid(True, axis="y", color="0.92", lw=0.5)
    ax_t.set_axisbelow(True)

    # Success rate: the other half of the score. 50 % is the ranking cutoff.
    rates = [r["success_rate"] * 100 for r in rows]
    ax_s.bar(x, rates, width=0.55, color=BAR)
    ax_s.axhline(50, color="0.15", lw=1.2, ls=":")
    ax_s.annotate("ranking cutoff", (x[-1] + 0.35, 50), fontsize=9,
                  ha="right", va="bottom", color="0.15")
    for i, r in enumerate(rates):
        ax_s.annotate(f"{r:.0f} %", (x[i], r), textcoords="offset points",
                      xytext=(0, 4), ha="center", fontsize=9)
    ax_s.set_xticks(x, labels)
    ax_s.set_ylim(0, 105)
    ax_s.set_ylabel("success rate  (%)")
    ax_s.set_title("Success (20 gates = 1 lap)")
    ax_s.grid(True, axis="y", color="0.92", lw=0.5)
    ax_s.set_axisbelow(True)

    fig.suptitle("Read them TOGETHER: a fast mean at low success is not a result",
                 fontsize=10, y=1.02)
    fig.tight_layout()
    fig.savefig(out, dpi=160, bbox_inches="tight")
    print(f"wrote {out}")


def main():
    # Fail BEFORE racing for ~10 minutes, not after: the figure needs this.
    try:
        import matplotlib  # noqa: F401
    except ImportError:
        sys.exit("matplotlib is missing in this venv — re-run "
                 "tasks/racing/setup.sh (or scripts/setup_python_envs.sh)")

    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("models", nargs="+",
                   help="label=path/to/policy.zip (one per model)")
    p.add_argument("--episodes", type=int, default=20,
                   help="Episodes per model (the leaderboard uses 20).")
    p.add_argument("--config", default="level0.toml",
                   help="Race config (level0.toml or level1.toml).")
    p.add_argument("--out-dir", type=Path, default=Path("tasks/racing/figures"))
    p.add_argument("--bridge", default="race_bridge.py",
                   help="controller file in repos/lsy_drone_racing/lsy_drone_racing/control/: "
                        "race_bridge.py (policies, Lesson 3) or race_bridge_mpc.py (Lesson 6)")
    p.add_argument("--start", choices=["ground", "hover"], default="ground",
                   help="ground = the leaderboard's start (default); hover = the same race with the "
                        "drone at rest at hover height (a generated *_hoverstart.toml), the "
                        "benchmark clock inside the race environment (Lesson 7)")
    p.add_argument("--no-poles", action="store_true",
                   help="race a generated *_nopoles.toml with the obstacle poles moved to the arena "
                        "corners: the pole-free benchmark of Lesson 7 (gate frames stay)")
    args = p.parse_args()
    if args.no_poles:
        args.config = no_poles_config(args.config)
        print(f"no poles: racing {args.config}")
    if args.start == "hover":
        args.config = hover_start_config(args.config)
        print(f"hover start: racing {args.config}")

    pairs = []
    for spec in args.models:
        label, _, value = spec.partition("=")
        if not value:
            label, value = Path(spec).parent.name, spec
        if is_policy_path(value):
            if not Path(value).exists():
                sys.exit(f"model not found: {value}")
        elif args.bridge == "race_bridge.py":
            sys.exit(f"{value!r} is not a policy .zip -- controller specs (mpc, datt:<zip>, ...) "
                     "need --bridge race_bridge_mpc.py (Lesson 6)")
        elif value.startswith("datt") and not Path(value.split(":", 1)[1]).exists():
            sys.exit(f"policy not found: {value.split(':', 1)[1]}")
        pairs.append((label, value))

    args.out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for label, model in pairs:
        print(f"\n=== {label}: {args.episodes} episodes on {args.config} via {args.bridge} ===")
        times = race(model, args.episodes, args.config, args.out_dir / label, args.bridge)
        rows.append(summarize(label, times))

    # ---- table ---------------------------------------------------------------
    print(f"\n{'model':<12} {'mean±std (s)':>16} {'best':>7} {'success':>10}  ranked?")
    for r in rows:
        ranked = "yes" if r["success_rate"] >= 0.5 else "NO — below 50 %"
        print(f"{r['label']:<12} {r['mean']:>9.3f}±{r['std']:.3f} "
              f"{r['best']:>7.3f} {r['successes']:>4d}/{r['episodes']:<3d}  {ranked}")
    print("\nleaderboard: 3.394 s all-time, 3.419 s current (at 100 % success)")

    # ---- csv -----------------------------------------------------------------
    csv_path = args.out_dir / "comparison.csv"
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["label", "episode", "time_s", "success"])
        for r in rows:
            for i, t in enumerate(r["times"]):
                w.writerow([r["label"], i, "" if t is None else f"{t:.4f}",
                            int(t is not None)])
    print(f"wrote {csv_path}")

    figure(rows, args.out_dir / "comparison.png")


if __name__ == "__main__":
    main()
